-- Contenido de ejemplo: El Portal de los Pasos Pequeños
-- Generado por supabase/build_setup.py. No editar a mano.

insert into public.courses (slug,title,summary,element,guardian,position,published) values ('primer-portal','El Portal de los Pasos Pequeños','Aprende a dividir un reto enorme en pasos que sí puedes terminar. Al final te espera Petrox, el gólem que cree que todo es demasiado grande.','naturaleza','petrox',1,true)
  on conflict (slug) do update set title=excluded.title, summary=excluded.summary, element=excluded.element, guardian=excluded.guardian, position=excluded.position, published=excluded.published;

insert into public.missions (id,course_slug,position,title,intro,xp_reward,is_boss) values ('95b561a6-728d-5a23-b6c4-637014f47fb7','primer-portal',1,'Cómo se come un elefante','Petrox dice que los retos grandes no se pueden vencer. Demuéstrale que se parten en trozos pequeños.',60,false)
  on conflict (id) do update set title=excluded.title, intro=excluded.intro, xp_reward=excluded.xp_reward, is_boss=excluded.is_boss;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('0661cc0f-a69c-524e-bcb2-42eb7efdea8f','95b561a6-728d-5a23-b6c4-637014f47fb7',1,'Tienes que armar una maqueta de tu barrio para el viernes. ¿Cuál es el mejor primer paso?','["Hacerla toda la noche del jueves", "Escribir una lista de las partes que necesita: casas, calles y parque", "Esperar a tener más tiempo", "Pedirle a alguien que la haga"]'::jsonb,1,'Piensa en qué te ayuda a saber por dónde empezar.','Una lista convierte un reto enorme en partes que puedes ir terminando una por una.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('d1a430c7-c65b-522c-b427-4e3c7f613eea','95b561a6-728d-5a23-b6c4-637014f47fb7',2,'¿Cuál de estas es una tarea pequeña y clara?','["Estudiar todo el libro", "Leer la página 12 y subrayar tres ideas", "Ser bueno en matemáticas", "Terminar el año"]'::jsonb,1,'Una tarea pequeña se puede terminar hoy y sabes cuándo acabó.','Es corta, concreta y sabes exactamente cuándo la terminaste.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('33b0ff92-f725-5049-aeb2-ad818390b021','95b561a6-728d-5a23-b6c4-637014f47fb7',3,'Si un reto parece enorme, ¿qué conviene hacer?','["Dividirlo en partes que puedas terminar en poco tiempo", "Ignorarlo", "Hacerlo todo de una vez", "Cambiar de tema"]'::jsonb,0,'Los gigantes se vencen por partes.','Dividir el reto lo hace manejable y te deja ver tu avance.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('0469c34b-06f1-54cf-b20e-6f5bcf0893b6','95b561a6-728d-5a23-b6c4-637014f47fb7',4,'Una receta tiene 10 pasos y te asustas. ¿Qué te ayuda más?','["Leer solo el último paso", "Hacer un paso, marcarlo y pasar al siguiente", "Saltarte los pasos difíciles", "Cocinar sin leer la receta"]'::jsonb,1,'Un paso a la vez.','Concentrarte en un solo paso y marcarlo reduce el miedo al total.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;

insert into public.missions (id,course_slug,position,title,intro,xp_reward,is_boss) values ('6e889cc2-7c34-5ca7-b04a-3a3e82ff532c','primer-portal',2,'Ordenar el camino','Los pasos pequeños también necesitan un orden. Ayuda a Kuro a ponerlos en fila.',60,false)
  on conflict (id) do update set title=excluded.title, intro=excluded.intro, xp_reward=excluded.xp_reward, is_boss=excluded.is_boss;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('489848fd-0e3f-5447-b690-693c5b4e119b','6e889cc2-7c34-5ca7-b04a-3a3e82ff532c',1,'Ordena para preparar un sándwich: 1) Poner el pan, 2) Lavarse las manos, 3) Comer, 4) Poner el relleno. ¿Cuál es el orden correcto?','["2, 1, 4, 3", "1, 2, 3, 4", "4, 1, 2, 3", "3, 2, 1, 4"]'::jsonb,0,'Antes de tocar la comida, ¿qué haces?','Primero te lavas las manos, luego armas el sándwich y al final lo comes.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('991a9d2e-0edc-5e35-be73-ead6a9988b05','6e889cc2-7c34-5ca7-b04a-3a3e82ff532c',2,'Para hacer un trabajo escrito, ¿qué va primero?','["Entregarlo", "Buscar información", "Escribir la conclusión", "Revisar la ortografía"]'::jsonb,1,'No puedes escribir sobre lo que aún no conoces.','Primero se reúne la información; después se escribe y, al final, se revisa y se entrega.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('5c80858a-e194-5cf7-9a78-2338e734e66c','6e889cc2-7c34-5ca7-b04a-3a3e82ff532c',3,'¿Por qué es útil ordenar los pasos?','["Porque así se ve más bonito", "Porque sabes qué hacer ahora y qué viene después", "Porque siempre lo piden", "Porque así tardas más"]'::jsonb,1,'Piensa en no perderte a la mitad.','Un orden claro te dice qué hacer ahora y evita que te bloquees.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('a77fa3a5-628e-5b4e-b3b5-2c18bb8edf61','6e889cc2-7c34-5ca7-b04a-3a3e82ff532c',4,'Un paso depende de otro cuando…','["Se puede hacer en cualquier momento", "No puedes hacerlo hasta terminar el anterior", "Es más corto", "Es más difícil"]'::jsonb,1,'Como poner el techo antes de hacer las paredes.','Hay pasos que necesitan que otro termine antes, por eso importa el orden.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;

insert into public.missions (id,course_slug,position,title,intro,xp_reward,is_boss) values ('58f63f94-3a15-5bc8-a58b-029f694f28df','primer-portal',3,'Pasos que caben en un día','Un buen plan no es el más largo, es el que sí puedes cumplir. Prepárate para el gólem.',70,false)
  on conflict (id) do update set title=excluded.title, intro=excluded.intro, xp_reward=excluded.xp_reward, is_boss=excluded.is_boss;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('68e0b904-7fb8-5c9c-a209-c441fc79c6c6','58f63f94-3a15-5bc8-a58b-029f694f28df',1,'Tienes tres tareas: una de 10 minutos, una de 30 y una de 2 horas. Hoy solo tienes 1 hora. ¿Qué plan es realista?','["Hacer las tres hoy", "Hacer las de 10 y 30 minutos hoy y partir la de 2 horas en bloques para otros días", "Hacer solo la de 2 horas", "No hacer ninguna"]'::jsonb,1,'Suma los minutos y compara con el tiempo que tienes.','Las dos cortas caben en una hora; la larga se divide en bloques para no abandonarla.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('e3fdee42-01a4-5267-851f-f1bb7ddf493d','58f63f94-3a15-5bc8-a58b-029f694f28df',2,'¿Cuál es una meta pequeña para hoy?','["Aprenderme todas las tablas", "Practicar la tabla del 6 durante 10 minutos", "Ser el mejor de la clase", "No equivocarme nunca"]'::jsonb,1,'Una meta pequeña tiene tiempo y resultado claros.','Tiene un tema, un tiempo y se puede cumplir hoy.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('f452d309-138c-5dac-9129-b34554aefe7e','58f63f94-3a15-5bc8-a58b-029f694f28df',3,'Si no logras terminar un paso, lo mejor es…','["Rendirte", "Revisar qué pasó y dividirlo en un paso más pequeño", "Esconderlo", "Hacer otra cosa y olvidarlo"]'::jsonb,1,'Un paso que no sale suele ser demasiado grande.','Partir el paso en uno más pequeño suele destrabarlo.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('7e2a43ac-07a8-5b66-9a94-c458807840a6','58f63f94-3a15-5bc8-a58b-029f694f28df',4,'Marcar cada paso terminado sirve para…','["Ver tu avance y motivarte", "Que otros te copien", "Gastar tinta", "Nada"]'::jsonb,0,'Ver el progreso da energía.','Ver lo que ya hiciste te motiva a seguir.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;

insert into public.missions (id,course_slug,position,title,intro,xp_reward,is_boss) values ('780d2631-5026-522d-a146-0974e16ab246','primer-portal',4,'Petrox, el gólem que cree que todo es demasiado grande','Es la prueba final del portal. Responde con calma: cada acierto parte un bloque de Petrox.',150,true)
  on conflict (id) do update set title=excluded.title, intro=excluded.intro, xp_reward=excluded.xp_reward, is_boss=excluded.is_boss;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('927bda1d-01f2-50c8-9c1c-2d206aae5b69','780d2631-5026-522d-a146-0974e16ab246',1,'Petrox te dice: «¡Este proyecto es enorme, no podrás!». ¿Qué respondes?','["Tienes razón, me rindo", "Lo divido en pasos pequeños y empiezo por el primero", "Lo hago todo mañana", "Lo copio de otra persona"]'::jsonb,1,'Recuerda cómo se vence a un gigante.','Dividir el proyecto y empezar por el primer paso es la forma de vencerlo.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('c2c70539-786e-5231-a23b-b1de87064ae7','780d2631-5026-522d-a146-0974e16ab246',2,'Para organizar una fiesta sorpresa, ¿qué orden tiene más sentido?','["Enviar invitaciones, elegir fecha, comprar el pastel", "Elegir fecha, enviar invitaciones, comprar el pastel", "Comprar el pastel, olvidar la fecha, invitar", "Invitar sin decir la fecha"]'::jsonb,1,'Para invitar necesitas saber cuándo es.','La fecha va primero porque las invitaciones y el pastel dependen de ella.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('e9af7621-aab7-5350-bb98-18a91a283d71','780d2631-5026-522d-a146-0974e16ab246',3,'¿Cuál es el mejor primer paso para estudiar para un examen?','["Mirar el tema cinco minutos antes", "Hacer una lista de los temas y escoger uno para hoy", "Dormir sin estudiar", "Estudiarlo todo en una noche"]'::jsonb,1,'Primero sabes qué hay que estudiar.','Una lista de temas y un tema para hoy convierten el examen en pasos.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('d77ca0d3-d1e8-5643-8895-a361b2c4373d','780d2631-5026-522d-a146-0974e16ab246',4,'Un paso pequeño debe ser…','["Vago y larguísimo", "Claro, corto y posible de terminar", "Imposible", "Secreto"]'::jsonb,1,'Recuerda la misión 1.','Si es claro, corto y posible, sabes cómo empezar y cuándo acabaste.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('65903d8a-f716-59dd-a3d6-fb8c21122748','780d2631-5026-522d-a146-0974e16ab246',5,'Si tienes 5 pasos y terminaste 3, ¿cuánto del camino llevas?','["Casi nada", "Más de la mitad", "Todo", "No se puede saber"]'::jsonb,1,'La mitad de 5 es 2,5.','3 de 5 es más de la mitad: ya vas por buen camino.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('e531b621-7804-58b6-91e4-247986e4f22c','780d2631-5026-522d-a146-0974e16ab246',6,'¿Qué aprendiste de Petrox?','["Que los retos grandes se vencen paso a paso", "Que mejor no intentarlo", "Que hay que hacerlo todo hoy", "Que los pasos no sirven"]'::jsonb,0,'Es la lección de todo el portal.','Cualquier montaña se sube paso a paso.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;

