-- Contenido de ejemplo: El Portal del Primer Intento
-- Generado por supabase/build_setup.py. No editar a mano.

insert into public.courses (slug,title,summary,element,guardian,position,published) values ('portal-del-primer-intento','El Portal del Primer Intento','Equivocarse no es perder: es parte de aprender. Al final te espera Ignaris, el dragón joven cuyas llamas se apagan cada vez que tiene miedo de intentarlo.','fuego','ignaris',2,true)
  on conflict (slug) do update set title=excluded.title, summary=excluded.summary, element=excluded.element, guardian=excluded.guardian, position=excluded.position, published=excluded.published;

insert into public.missions (id,course_slug,position,title,intro,xp_reward,is_boss) values ('60a71a72-6b6d-5140-a936-044b789148e5','portal-del-primer-intento',1,'La llama del primer intento','Ignaris no se atreve a empezar nada por miedo a hacerlo mal. Muéstrale que el primer paso no tiene que ser perfecto.',60,false)
  on conflict (id) do update set title=excluded.title, intro=excluded.intro, xp_reward=excluded.xp_reward, is_boss=excluded.is_boss;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('6e65b9a7-4bb3-5470-82c9-0b2fcd9de8b5','60a71a72-6b6d-5140-a936-044b789148e5',1,'Tienes que escribir un cuento y la hoja en blanco te da miedo. ¿Cuál es el mejor primer paso?','["Esperar a tener la idea perfecta", "Escribir una primera frase, aunque no sea perfecta", "Copiar un cuento de internet", "Dejarlo para el último día"]'::jsonb,1,'Un borrador se puede mejorar; una hoja en blanco, no.','Empezar con algo imperfecto te da material para mejorar. La idea perfecta casi nunca llega mientras esperas.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('37de0298-4374-515a-b5bd-cd27576c1fa0','60a71a72-6b6d-5140-a936-044b789148e5',2,'Valentina quiere aprender a montar en bicicleta, pero le da miedo caerse. ¿Qué le ayuda más?','["Practicar en un lugar seguro, con casco y poco a poco", "No intentarlo nunca", "Bajar una loma muy empinada el primer día", "Solo ver videos, sin subirse nunca"]'::jsonb,0,'El miedo baja cuando el primer intento es pequeño y seguro.','Un primer intento pequeño y seguro reduce el miedo y te deja aprender sin arriesgar demasiado.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('5554f901-6b53-5ef5-aaca-b2d633facb3e','60a71a72-6b6d-5140-a936-044b789148e5',3,'¿Qué significa decir «todavía no me sale»?','["Que nunca te va a salir", "Que no eres bueno para eso", "Que estás aprendiendo y con práctica te puede salir", "Que es culpa de otra persona"]'::jsonb,2,'Fíjate en la palabra «todavía».','«Todavía» significa que vas en camino: con práctica, lo que hoy no sale mañana puede salir.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('1177d6bd-5b05-598a-8af4-940b7c7c4522','60a71a72-6b6d-5140-a936-044b789148e5',4,'Antes de un examen sientes nervios. ¿Qué es cierto?','["Sentir nervios es normal y puedes responder igual", "Los nervios significan que te va a ir mal", "Si tienes nervios, mejor no presentarlo", "Solo sienten nervios los que no estudiaron"]'::jsonb,0,'Hasta los deportistas profesionales sienten nervios antes de jugar.','Los nervios son normales cuando algo te importa. Respirar despacio y empezar por una pregunta fácil ayuda mucho.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;

insert into public.missions (id,course_slug,position,title,intro,xp_reward,is_boss) values ('9f57076b-f4a7-5529-9db9-8e108c73252c','portal-del-primer-intento',2,'Los errores son pistas','Cada error deja una huella que dice por dónde seguir. Ayuda a Kuro a leerlas.',60,false)
  on conflict (id) do update set title=excluded.title, intro=excluded.intro, xp_reward=excluded.xp_reward, is_boss=excluded.is_boss;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('adabac70-1b70-5213-8f25-504b8794634a','9f57076b-f4a7-5529-9db9-8e108c73252c',1,'Te equivocaste en una suma. ¿Qué es lo más útil?','["Borrar todo y no volver a mirarla", "Revisar en qué paso estuvo el error", "Decir que las matemáticas no son para ti", "Pedir que no cuenten esa tarea"]'::jsonb,1,'Un error te dice dónde mirar.','Encontrar el paso exacto del error te enseña qué practicar y evita que lo repitas.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('734ca0fd-a0eb-5421-bd4f-8a3c3b6d9f3b','9f57076b-f4a7-5529-9db9-8e108c73252c',2,'Una científica prueba una idea y no funciona. ¿Qué hace?','["Anota qué pasó y prueba un cambio", "Esconde los resultados", "Deja la ciencia para siempre", "Repite exactamente lo mismo cien veces"]'::jsonb,0,'Un experimento que falla también da información.','Cada intento que no funciona descarta una posibilidad y acerca la respuesta. Por eso en ciencia se anotan los errores.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('bbced9bf-197e-5b93-99a0-34ca1ee5a558','9f57076b-f4a7-5529-9db9-8e108c73252c',3,'¿Cuál de estas frases trata al error como una pista?','["Soy un desastre", "Esto no es para mí", "Ya sé que este camino no funciona; probaré otro", "Nunca más lo intento"]'::jsonb,2,'Busca la frase que mira hacia adelante.','Esa frase convierte el error en información: ya sabes qué no funciona y puedes probar otra cosa.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('a006ac7a-64be-56c2-a354-84bb1746a268','9f57076b-f4a7-5529-9db9-8e108c73252c',4,'Tu profesora te devuelve el trabajo con correcciones. ¿Para qué sirven?','["Para hacerte sentir mal", "Para mostrarte qué mejorar en el próximo intento", "Para que no vuelvas a entregar trabajos", "Para nada; mejor no leerlas"]'::jsonb,1,'Las correcciones son como un mapa.','Las correcciones señalan exactamente qué mejorar. Leerlas es la forma más rápida de avanzar.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;

insert into public.missions (id,course_slug,position,title,intro,xp_reward,is_boss) values ('ee43a599-93b0-5c2b-a86b-4b0b00447f8d','portal-del-primer-intento',3,'Intentarlo de otra manera','Repetir lo mismo da el mismo resultado. Aprende a cambiar de estrategia antes de enfrentar al dragón.',70,false)
  on conflict (id) do update set title=excluded.title, intro=excluded.intro, xp_reward=excluded.xp_reward, is_boss=excluded.is_boss;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('9676ac66-5dce-5aa6-8b59-eeea2d8a0b71','ee43a599-93b0-5c2b-a86b-4b0b00447f8d',1,'Llevas un rato con un problema y no te sale. ¿Qué puedes probar?','["Hacer lo mismo, pero más rápido", "Rendirte y no volver a intentarlo", "Hacer un dibujo o un esquema del problema", "Esperar a que se resuelva solo"]'::jsonb,2,'Cambia la forma de mirarlo.','Cambiar de estrategia, por ejemplo dibujando el problema, muchas veces deja ver lo que antes no veías.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('39c28e08-292d-5b33-85d3-5ad77d7dee59','ee43a599-93b0-5c2b-a86b-4b0b00447f8d',2,'¿Cuándo es buena idea pedir ayuda?','["Nunca: pedir ayuda es de débiles", "Después de intentarlo y saber qué parte no entiendes", "Antes de leer la pregunta", "Solo si nadie te ve"]'::jsonb,1,'Pedir ayuda funciona mejor cuando sabes qué preguntar.','Pedir ayuda es una estrategia de los buenos aprendices. Funciona mejor si ya lo intentaste y sabes qué parte te traba.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('d89593a9-b170-5c9c-9d40-4b355a917d8b','ee43a599-93b0-5c2b-a86b-4b0b00447f8d',3,'Sebastián falla el mismo tiro libre varias veces. ¿Qué le ayuda más?','["Cambiar una cosa pequeña en cada intento y fijarse en el resultado", "Patear más fuerte sin pensar", "Culpar al balón", "Dejar de practicar"]'::jsonb,0,'Probar, mirar y ajustar.','Ajustar una sola cosa a la vez y observar qué pasa es la forma en que mejoran los deportistas.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('695f4cd5-260a-5256-a70a-4270c8959387','ee43a599-93b0-5c2b-a86b-4b0b00447f8d',4,'Después de varios intentos lograste algo difícil. ¿Qué aprendiste?','["Que tuviste suerte", "Que era fácil desde el principio", "Que ya no necesitas aprender nada más", "Que la práctica y los intentos te hicieron mejorar"]'::jsonb,3,'Piensa en todo lo que pasó antes del logro.','No fue suerte: cada intento te enseñó algo. Recordarlo te da valor para el siguiente reto.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;

insert into public.missions (id,course_slug,position,title,intro,xp_reward,is_boss) values ('dde52c31-4a94-50ff-86b9-084ac1e3d9a5','portal-del-primer-intento',4,'Ignaris, el dragón que teme equivocarse','Las llamas de Ignaris se apagan cada vez que duda. Enséñale que equivocarse es parte de aprender y su fuego volverá a brillar.',150,true)
  on conflict (id) do update set title=excluded.title, intro=excluded.intro, xp_reward=excluded.xp_reward, is_boss=excluded.is_boss;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('22e8e0c0-cb1b-5902-b4d6-2aaf86a51180','dde52c31-4a94-50ff-86b9-084ac1e3d9a5',1,'Ignaris ruge: «¡Si me equivoco, todos se van a reír de mí!». ¿Qué le respondes?','["Tienes razón, mejor no lo intentes", "Todos nos equivocamos al aprender; lo importante es seguir intentando", "Haz que otro lo haga por ti", "Equivócate a escondidas"]'::jsonb,1,'¿Conoces a alguien que haya aprendido algo sin equivocarse nunca?','Equivocarse es parte de aprender para todo el mundo. Quien sigue intentando es quien mejora.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('2c279222-3bb2-5c9b-98cd-db661b901f36','dde52c31-4a94-50ff-86b9-084ac1e3d9a5',2,'¿Cuál es el mejor primer paso ante una tarea que te da miedo?','["Esperar a dejar de sentir miedo", "Hacerla toda de una vez esta noche", "Empezar por una parte pequeña durante cinco minutos", "Decir que ya la hiciste"]'::jsonb,2,'Empezar pequeño apaga el miedo.','Cinco minutos con una parte pequeña rompen el bloqueo; casi siempre, después es más fácil seguir.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('8c46fba9-a5e3-58e9-b9dc-68f9a34884d5','dde52c31-4a94-50ff-86b9-084ac1e3d9a5',3,'Te equivocaste en una pregunta de esta misma prueba. ¿Qué haces?','["Leo la explicación para entender por qué", "Cierro la página y no vuelvo", "Pienso que no sirvo para esto", "Culpo a la pregunta"]'::jsonb,0,'El repaso del final está ahí por algo.','La explicación convierte el error en aprendizaje, y en el siguiente intento lo harás mejor.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('773df992-f6cb-5913-807e-86ab2e8dfa05','dde52c31-4a94-50ff-86b9-084ac1e3d9a5',4,'¿Cuál de estas frases ayuda a Ignaris a volver a intentarlo?','["Nunca voy a poder", "Es imposible", "Los demás son mejores que yo", "Todavía no me sale, pero voy a probar otra forma"]'::jsonb,3,'Busca la frase que abre una puerta.','«Todavía» y «otra forma» convierten un tropiezo en un plan para el próximo intento.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('0f14e8a0-3a69-55d0-8490-af8465ef7cfa','dde52c31-4a94-50ff-86b9-084ac1e3d9a5',5,'Intentaste algo tres veces de la misma manera y no salió. ¿Qué conviene?','["Intentarlo igual una cuarta vez", "Cambiar de estrategia o pedir ayuda", "Abandonarlo para siempre", "Esconder que no te salió"]'::jsonb,1,'Si un camino no te lleva, prueba otro.','Repetir lo mismo da el mismo resultado; cambiar de estrategia o pedir ayuda abre caminos nuevos.')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;
insert into public.questions (id,mission_id,position,prompt,options,correct_index,hint,explanation) values ('1ca4c12f-0a59-5e9c-b877-113d5f9935b2','dde52c31-4a94-50ff-86b9-084ac1e3d9a5',6,'Al final, ¿qué apaga el miedo de Ignaris?','["Probar, equivocarse, aprender y volver a intentar", "No intentar nada nuevo", "Hacer solo lo que ya sabe", "Esperar a ser perfecto"]'::jsonb,0,'Es la habilidad que vence a este Guardián.','Probar, equivocarse y reintentar es la forma de aprender cualquier cosa. ¡Con eso purificas a Ignaris!')
  on conflict (id) do update set prompt=excluded.prompt, options=excluded.options, correct_index=excluded.correct_index, hint=excluded.hint, explanation=excluded.explanation;

